"""Initial migration.

Revision ID: cb7170519043
Revises: 
Create Date: 2020-03-26 20:48:27.757283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7170519043'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fname', sa.String(), nullable=False))
    op.add_column('users', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'timestamp')
    op.drop_column('users', 'fname')
    # ### end Alembic commands ###
